export const AUTH = 'http://localhost:1337/api/auth/local'
export const PRODUCTS = 'http://localhost:1337/api/products?populate=category&populate=brand&populate=image'
export const PRODUCT = 'http://localhost:1337/api/products/id?populate=category&populate=brand&populate=image&populate=reviews'
export const BRANDS = 'http://localhost:1337/api/brands'
export const CATEGORIES = 'http://localhost:1337/api/categories'